In [1]:
using DataFrames

In [58]:
using ScikitLearn

In [57]:
using ScikitLearn:fit!,predict

In [3]:
using CSV

In [4]:
using Statistics

In [5]:
using CategoricalArrays
using MLBase

In [6]:
train = CSV.read("train.csv")

891×12 DataFrame. Omitted printing of 9 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 1           │ 0        │ 3      │
│ 2   │ 2           │ 1        │ 1      │
│ 3   │ 3           │ 1        │ 3      │
│ 4   │ 4           │ 1        │ 1      │
│ 5   │ 5           │ 0        │ 3      │
│ 6   │ 6           │ 0        │ 3      │
│ 7   │ 7           │ 0        │ 1      │
│ 8   │ 8           │ 0        │ 3      │
│ 9   │ 9           │ 1        │ 3      │
│ 10  │ 10          │ 1        │ 2      │
⋮
│ 881 │ 881         │ 1        │ 2      │
│ 882 │ 882         │ 0        │ 3      │
│ 883 │ 883         │ 0        │ 3      │
│ 884 │ 884         │ 0        │ 2      │
│ 885 │ 885         │ 0        │ 3      │
│ 886 │ 886         │ 0        │ 3      │
│ 887 │ 887         │ 0        │ 2      │
│ 888 │ 888         │ 1        │ 1      │
│ 889 │ 889         │ 0        │ 3      │
│ 890 │ 890         │ 1        │ 1      │
│ 891 │ 891         │ 0        │ 3      │

In [7]:
first(train,3)

3×12 DataFrame. Omitted printing of 9 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 1           │ 0        │ 3      │
│ 2   │ 2           │ 1        │ 1      │
│ 3   │ 3           │ 1        │ 3      │

In [8]:
last(train,3)

3×12 DataFrame. Omitted printing of 9 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 889         │ 0        │ 3      │
│ 2   │ 890         │ 1        │ 1      │
│ 3   │ 891         │ 0        │ 3      │

In [9]:
ismissing(train)

false

In [10]:
test = CSV.read("test.csv")

418×11 DataFrame. Omitted printing of 8 columns
│ Row │ PassengerId │ Pclass │ Name                                            │
│     │ Int64       │ Int64  │ String                                          │
├─────┼─────────────┼────────┼─────────────────────────────────────────────────┤
│ 1   │ 892         │ 3      │ Kelly, Mr. James                                │
│ 2   │ 893         │ 3      │ Wilkes, Mrs. James (Ellen Needs)                │
│ 3   │ 894         │ 2      │ Myles, Mr. Thomas Francis                       │
│ 4   │ 895         │ 3      │ Wirz, Mr. Albert                                │
│ 5   │ 896         │ 3      │ Hirvonen, Mrs. Alexander (Helga E Lindqvist)    │
│ 6   │ 897         │ 3      │ Svensson, Mr. Johan Cervin                      │
│ 7   │ 898         │ 3      │ Connolly, Miss. Kate                            │
│ 8   │ 899         │ 2      │ Caldwell, Mr. Albert Francis                    │
│ 9   │ 900         │ 3      │ Abrahim, Mrs. Joseph (Sophie Halaut Easu)       │
│ 10  │ 901         │ 3      │ Davies, Mr. John Samuel                         │
⋮
│ 408 │ 1299        │ 1      │ Widener, Mr. George Dunton                      │
│ 409 │ 1300        │ 3      │ Riordan, Miss. Johanna Hannah""                 │
│ 410 │ 1301        │ 3      │ Peacock, Miss. Treasteall                       │
│ 411 │ 1302        │ 3      │ Naughton, Miss. Hannah                          │
│ 412 │ 1303        │ 1      │ Minahan, Mrs. William Edward (Lillian E Thorpe) │
│ 413 │ 1304        │ 3      │ Henriksson, Miss. Jenny Lovisa                  │
│ 414 │ 1305        │ 3      │ Spector, Mr. Woolf                              │
│ 415 │ 1306        │ 1      │ Oliva y Ocana, Dona. Fermina                    │
│ 416 │ 1307        │ 3      │ Saether, Mr. Simon Sivertsen                    │
│ 417 │ 1308        │ 3      │ Ware, Mr. Frederick                             │
│ 418 │ 1309        │ 3      │ Peter, Master. Michael J                        │

In [11]:
ismissing(test)

false

In [12]:
?describe

search: describe



```
describe(io::IO, x)
```

For an object `x`, print descriptive statistics to `io`.

This generic function is owned by StatsBase.jl, which is the sole provider of the default definition.

---

```
describe(df::AbstractDataFrame; cols=:)
describe(df::AbstractDataFrame, stats::Union{Symbol, Pair}...; cols=:)
```

Return descriptive statistics for a data frame as a new `DataFrame` where each row represents a variable and each column a summary statistic.

# Arguments

  * `df` : the `AbstractDataFrame`
  * `stats::Union{Symbol, Pair}...` : the summary statistics to report. Arguments can be:

      * A symbol from the list `:mean`, `:std`, `:min`, `:q25`, `:median`, `:q75`, `:max`, `:eltype`, `:nunique`, `:first`, `:last`, and `:nmissing`. The default statistics used are `:mean`, `:min`, `:median`, `:max`, `:nunique`, `:nmissing`, and `:eltype`.
      * `:all` as the only `Symbol` argument to return all statistics.
      * A `name => function` pair where `name` is a `Symbol` or string. This will create a column of summary statistics with the provided name.
  * `cols` : a keyword argument allowing to select only a subset of columns from `df` to describe. Can be any column selector (`Symbol`, string or integer; `:`, `All`, `Between`, `Not`, a regular expression, or a vector of `Symbol`s, strings or integers).

# Details

For `Real` columns, compute the mean, standard deviation, minimum, first quantile, median, third quantile, and maximum. If a column does not derive from `Real`, `describe` will attempt to calculate all statistics, using `nothing` as a fall-back in the case of an error.

When `stats` contains `:nunique`, `describe` will report the number of unique values in a column. If a column's base type derives from `Real`, `:nunique` will return `nothing`s.

Missing values are filtered in the calculation of all statistics, however the column `:nmissing` will report the number of missing values of that variable. If the column does not allow missing values, `nothing` is returned. Consequently, `nmissing = 0` indicates that the column allows missing values, but does not currently contain any.

If custom functions are provided, they are called repeatedly with the vector corresponding to each column as the only argument. For columns allowing for missing values, the vector is wrapped in a call to `skipmissing`: custom functions must therefore support such objects (and not only vectors), and cannot access missing values.

# Examples

```julia
julia> df = DataFrame(i=1:10, x=0.1:0.1:1.0, y='a':'j')
10×3 DataFrame
│ Row │ i     │ x       │ y    │
│     │ Int64 │ Float64 │ Char │
├─────┼───────┼─────────┼──────┤
│ 1   │ 1     │ 0.1     │ 'a'  │
│ 2   │ 2     │ 0.2     │ 'b'  │
│ 3   │ 3     │ 0.3     │ 'c'  │
│ 4   │ 4     │ 0.4     │ 'd'  │
│ 5   │ 5     │ 0.5     │ 'e'  │
│ 6   │ 6     │ 0.6     │ 'f'  │
│ 7   │ 7     │ 0.7     │ 'g'  │
│ 8   │ 8     │ 0.8     │ 'h'  │
│ 9   │ 9     │ 0.9     │ 'i'  │
│ 10  │ 10    │ 1.0     │ 'j'  │

julia> describe(df)
3×8 DataFrame
│ Row │ variable │ mean   │ min │ median │ max │ nunique │ nmissing │ eltype   │
│     │ Symbol   │ Union… │ Any │ Union… │ Any │ Union…  │ Nothing  │ DataType │
├─────┼──────────┼────────┼─────┼────────┼─────┼─────────┼──────────┼──────────┤
│ 1   │ i        │ 5.5    │ 1   │ 5.5    │ 10  │         │          │ Int64    │
│ 2   │ x        │ 0.55   │ 0.1 │ 0.55   │ 1.0 │         │          │ Float64  │
│ 3   │ y        │        │ 'a' │        │ 'j' │ 10      │          │ Char     │

julia> describe(df, :min, :max)
3×3 DataFrame
│ Row │ variable │ min │ max │
│     │ Symbol   │ Any │ Any │
├─────┼──────────┼─────┼─────┤
│ 1   │ i        │ 1   │ 10  │
│ 2   │ x        │ 0.1 │ 1.0 │
│ 3   │ y        │ 'a' │ 'j' │

julia> describe(df, :min, :sum => sum)
3×3 DataFrame
│ Row │ variable │ min │ sum │
│     │ Symbol   │ Any │ Any │
├─────┼──────────┼─────┼─────┤
│ 1   │ i        │ 1   │ 55  │
│ 2   │ x        │ 0.1 │ 5.5 │
│ 3   │ y        │ 'a' │     │

julia> describe(df, :min, :sum => sum, cols=:x)
1×3 DataFrame
│ Row │ variable │ min     │ sum     │
│     │ Symbol   │ Float64 │ Float64 │
├─────┼──────────┼─────────┼─────────┤
│ 1   │ x        │ 0.1     │ 5.5     │
```

---

```
describe(a)
```

Pretty-print the summary statistics provided by [`summarystats`](@ref): the mean, minimum, 25th percentile, median, 75th percentile, and maximum.


In [13]:
showall(describe(train))

┌ Warning: `showall(df::AbstractDataFrame, allcols::Bool = true)` is deprecated, use `show(df, allrows = true, allcols = allcols)` instead.
│   caller = showall(::DataFrame) at deprecated.jl:66
└ @ DataFrames .\deprecated.jl:66


12×8 DataFrame
│ Row │ variable    │ mean     │ min                 │ median  │
│     │ Symbol      │ Union…   │ Any                 │ Union…  │
├─────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1   │ PassengerId │ 446.0    │ 1                   │ 446.0   │
│ 2   │ Survived    │ 0.383838 │ 0                   │ 0.0     │
│ 3   │ Pclass      │ 2.30864  │ 1                   │ 3.0     │
│ 4   │ Name        │          │ Abbing, Mr. Anthony │         │
│ 5   │ Sex         │          │ female              │         │
│ 6   │ Age         │ 29.6991  │ 0.42                │ 28.0    │
│ 7   │ SibSp       │ 0.523008 │ 0                   │ 0.0     │
│ 8   │ Parch       │ 0.381594 │ 0                   │ 0.0     │
│ 9   │ Ticket      │          │ 110152              │         │
│ 10  │ Fare        │ 32.2042  │ 0.0                 │ 14.4542 │
│ 11  │ Cabin       │          │ A10                 │         │
│ 12  │ Embarked    │          │ C                   │         │

│ Row │ m

In [14]:
train = DataFrame(train)

891×12 DataFrame. Omitted printing of 9 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 1           │ 0        │ 3      │
│ 2   │ 2           │ 1        │ 1      │
│ 3   │ 3           │ 1        │ 3      │
│ 4   │ 4           │ 1        │ 1      │
│ 5   │ 5           │ 0        │ 3      │
│ 6   │ 6           │ 0        │ 3      │
│ 7   │ 7           │ 0        │ 1      │
│ 8   │ 8           │ 0        │ 3      │
│ 9   │ 9           │ 1        │ 3      │
│ 10  │ 10          │ 1        │ 2      │
⋮
│ 881 │ 881         │ 1        │ 2      │
│ 882 │ 882         │ 0        │ 3      │
│ 883 │ 883         │ 0        │ 3      │
│ 884 │ 884         │ 0        │ 2      │
│ 885 │ 885         │ 0        │ 3      │
│ 886 │ 886         │ 0        │ 3      │
│ 887 │ 887         │ 0        │ 2      │
│ 888 │ 888         │ 1        │ 1      │
│ 889 │ 889         │ 0        │ 3      │
│ 890 │ 890         │ 1        │ 1      │
│ 891 │ 891         │ 0        │ 3      │

In [15]:
test = DataFrame(test)

418×11 DataFrame. Omitted printing of 8 columns
│ Row │ PassengerId │ Pclass │ Name                                            │
│     │ Int64       │ Int64  │ String                                          │
├─────┼─────────────┼────────┼─────────────────────────────────────────────────┤
│ 1   │ 892         │ 3      │ Kelly, Mr. James                                │
│ 2   │ 893         │ 3      │ Wilkes, Mrs. James (Ellen Needs)                │
│ 3   │ 894         │ 2      │ Myles, Mr. Thomas Francis                       │
│ 4   │ 895         │ 3      │ Wirz, Mr. Albert                                │
│ 5   │ 896         │ 3      │ Hirvonen, Mrs. Alexander (Helga E Lindqvist)    │
│ 6   │ 897         │ 3      │ Svensson, Mr. Johan Cervin                      │
│ 7   │ 898         │ 3      │ Connolly, Miss. Kate                            │
│ 8   │ 899         │ 2      │ Caldwell, Mr. Albert Francis                    │
│ 9   │ 900         │ 3      │ Abrahim, Mrs. Joseph (Sophie Halaut Easu)       │
│ 10  │ 901         │ 3      │ Davies, Mr. John Samuel                         │
⋮
│ 408 │ 1299        │ 1      │ Widener, Mr. George Dunton                      │
│ 409 │ 1300        │ 3      │ Riordan, Miss. Johanna Hannah""                 │
│ 410 │ 1301        │ 3      │ Peacock, Miss. Treasteall                       │
│ 411 │ 1302        │ 3      │ Naughton, Miss. Hannah                          │
│ 412 │ 1303        │ 1      │ Minahan, Mrs. William Edward (Lillian E Thorpe) │
│ 413 │ 1304        │ 3      │ Henriksson, Miss. Jenny Lovisa                  │
│ 414 │ 1305        │ 3      │ Spector, Mr. Woolf                              │
│ 415 │ 1306        │ 1      │ Oliva y Ocana, Dona. Fermina                    │
│ 416 │ 1307        │ 3      │ Saether, Mr. Simon Sivertsen                    │
│ 417 │ 1308        │ 3      │ Ware, Mr. Frederick                             │
│ 418 │ 1309        │ 3      │ Peter, Master. Michael J                        │

In [16]:
showall(describe(test))

11×8 DataFrame
│ Row │ variable    │ mean     │ min                           │ median  │
│     │ Symbol      │ Union…   │ Any                           │ Union…  │
├─────┼─────────────┼──────────┼───────────────────────────────┼─────────┤
│ 1   │ PassengerId │ 1100.5   │ 892                           │ 1100.5  │
│ 2   │ Pclass      │ 2.26555  │ 1                             │ 3.0     │
│ 3   │ Name        │          │ Abbott, Master. Eugene Joseph │         │
│ 4   │ Sex         │          │ female                        │         │
│ 5   │ Age         │ 30.2726  │ 0.17                          │ 27.0    │
│ 6   │ SibSp       │ 0.447368 │ 0                             │ 0.0     │
│ 7   │ Parch       │ 0.392344 │ 0                             │ 0.0     │
│ 8   │ Ticket      │          │ 110469                        │         │
│ 9   │ Fare        │ 35.6272  │ 0.0                           │ 14.4542 │
│ 10  │ Cabin       │          │ A11                           │         │
│ 11  │ Em

In [17]:
select!(train,Not(:Cabin))

891×11 DataFrame. Omitted printing of 8 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 1           │ 0        │ 3      │
│ 2   │ 2           │ 1        │ 1      │
│ 3   │ 3           │ 1        │ 3      │
│ 4   │ 4           │ 1        │ 1      │
│ 5   │ 5           │ 0        │ 3      │
│ 6   │ 6           │ 0        │ 3      │
│ 7   │ 7           │ 0        │ 1      │
│ 8   │ 8           │ 0        │ 3      │
│ 9   │ 9           │ 1        │ 3      │
│ 10  │ 10          │ 1        │ 2      │
⋮
│ 881 │ 881         │ 1        │ 2      │
│ 882 │ 882         │ 0        │ 3      │
│ 883 │ 883         │ 0        │ 3      │
│ 884 │ 884         │ 0        │ 2      │
│ 885 │ 885         │ 0        │ 3      │
│ 886 │ 886         │ 0        │ 3      │
│ 887 │ 887         │ 0        │ 2      │
│ 888 │ 888         │ 1        │ 1      │
│ 889 │ 889         │ 0        │ 3      │
│ 890 │ 890         │ 1        │ 1      │
│ 891 │ 891         │ 0        │ 3      │

In [18]:
select!(test,Not(:Cabin))

418×10 DataFrame. Omitted printing of 7 columns
│ Row │ PassengerId │ Pclass │ Name                                            │
│     │ Int64       │ Int64  │ String                                          │
├─────┼─────────────┼────────┼─────────────────────────────────────────────────┤
│ 1   │ 892         │ 3      │ Kelly, Mr. James                                │
│ 2   │ 893         │ 3      │ Wilkes, Mrs. James (Ellen Needs)                │
│ 3   │ 894         │ 2      │ Myles, Mr. Thomas Francis                       │
│ 4   │ 895         │ 3      │ Wirz, Mr. Albert                                │
│ 5   │ 896         │ 3      │ Hirvonen, Mrs. Alexander (Helga E Lindqvist)    │
│ 6   │ 897         │ 3      │ Svensson, Mr. Johan Cervin                      │
│ 7   │ 898         │ 3      │ Connolly, Miss. Kate                            │
│ 8   │ 899         │ 2      │ Caldwell, Mr. Albert Francis                    │
│ 9   │ 900         │ 3      │ Abrahim, Mrs. Joseph (Sophie Halaut Easu)       │
│ 10  │ 901         │ 3      │ Davies, Mr. John Samuel                         │
⋮
│ 408 │ 1299        │ 1      │ Widener, Mr. George Dunton                      │
│ 409 │ 1300        │ 3      │ Riordan, Miss. Johanna Hannah""                 │
│ 410 │ 1301        │ 3      │ Peacock, Miss. Treasteall                       │
│ 411 │ 1302        │ 3      │ Naughton, Miss. Hannah                          │
│ 412 │ 1303        │ 1      │ Minahan, Mrs. William Edward (Lillian E Thorpe) │
│ 413 │ 1304        │ 3      │ Henriksson, Miss. Jenny Lovisa                  │
│ 414 │ 1305        │ 3      │ Spector, Mr. Woolf                              │
│ 415 │ 1306        │ 1      │ Oliva y Ocana, Dona. Fermina                    │
│ 416 │ 1307        │ 3      │ Saether, Mr. Simon Sivertsen                    │
│ 417 │ 1308        │ 3      │ Ware, Mr. Frederick                             │
│ 418 │ 1309        │ 3      │ Peter, Master. Michael J                        │

In [19]:
mean(skipmissing(train["Age"]))

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[19]:1
└ @ Core In[19]:1


29.69911764705882

In [20]:
train["Age"]=coalesce.(train["Age"],ceil(mean(skipmissing(train["Age"]))))

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[20]:1
└ @ Core In[20]:1
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[20]:1
└ @ Core In[20]:1
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = top-level scope at In[20]:1
└ @ Core In[20]:1


891-element Array{Float64,1}:
 22.0
 38.0
 26.0
 35.0
 35.0
 30.0
 54.0
  2.0
 27.0
 14.0
  4.0
 58.0
 20.0
  ⋮
 56.0
 25.0
 33.0
 22.0
 28.0
 25.0
 39.0
 27.0
 19.0
 30.0
 26.0
 32.0

In [21]:
#coalesce.(test["Age"],ceil(mean(skipmissing(test["Age"]))))

test.Age = replace(test.Age,missing =>ceil(mean(skipmissing(test["Age"]))) )

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[21]:1
└ @ Core In[21]:1


418-element Array{Float64,1}:
 34.5
 47.0
 62.0
 27.0
 22.0
 14.0
 30.0
 26.0
 18.0
 21.0
 31.0
 46.0
 23.0
  ⋮
 23.0
 50.0
 31.0
  3.0
 31.0
 37.0
 28.0
 31.0
 39.0
 38.5
 31.0
 31.0

In [22]:
train.Embarked = coalesce.(train["Embarked"],"S")

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[22]:1
└ @ Core In[22]:1


891-element Array{String,1}:
 "S"
 "C"
 "S"
 "S"
 "S"
 "Q"
 "S"
 "S"
 "S"
 "C"
 "S"
 "S"
 "S"
 ⋮
 "C"
 "S"
 "S"
 "S"
 "S"
 "S"
 "Q"
 "S"
 "S"
 "S"
 "C"
 "Q"

In [23]:
test.Fare = coalesce.(test["Fare"],35)

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[23]:1
└ @ Core In[23]:1


418-element Array{Real,1}:
   7.8292
   7.0
   9.6875
   8.6625
  12.2875
   9.225
   7.6292
  29.0
   7.2292
  24.15
   7.8958
  26.0
  82.2667
   ⋮
  10.5
 211.5
   7.7208
  13.775
   7.75
  90.0
   7.775
   8.05
 108.9
   7.25
   8.05
  22.3583

In [24]:
test.Embarked = coalesce.(test["Embarked"],"S")

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[24]:1
└ @ Core In[24]:1


418-element Array{String,1}:
 "Q"
 "S"
 "Q"
 "S"
 "S"
 "S"
 "Q"
 "S"
 "C"
 "S"
 "S"
 "S"
 "S"
 ⋮
 "S"
 "C"
 "Q"
 "S"
 "Q"
 "Q"
 "S"
 "S"
 "C"
 "S"
 "S"
 "C"

In [25]:
showall(describe(train))

11×8 DataFrame
│ Row │ variable    │ mean     │ min                 │ median  │
│     │ Symbol      │ Union…   │ Any                 │ Union…  │
├─────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1   │ PassengerId │ 446.0    │ 1                   │ 446.0   │
│ 2   │ Survived    │ 0.383838 │ 0                   │ 0.0     │
│ 3   │ Pclass      │ 2.30864  │ 1                   │ 3.0     │
│ 4   │ Name        │          │ Abbing, Mr. Anthony │         │
│ 5   │ Sex         │          │ female              │         │
│ 6   │ Age         │ 29.7589  │ 0.42                │ 30.0    │
│ 7   │ SibSp       │ 0.523008 │ 0                   │ 0.0     │
│ 8   │ Parch       │ 0.381594 │ 0                   │ 0.0     │
│ 9   │ Ticket      │          │ 110152              │         │
│ 10  │ Fare        │ 32.2042  │ 0.0                 │ 14.4542 │
│ 11  │ Embarked    │          │ C                   │         │

│ Row │ max                         │ nunique │ nmissing │ eltype   │
│   

In [26]:
showall(describe(test))

10×8 DataFrame
│ Row │ variable    │ mean     │ min                           │ median  │
│     │ Symbol      │ Union…   │ Any                           │ Union…  │
├─────┼─────────────┼──────────┼───────────────────────────────┼─────────┤
│ 1   │ PassengerId │ 1100.5   │ 892                           │ 1100.5  │
│ 2   │ Pclass      │ 2.26555  │ 1                             │ 3.0     │
│ 3   │ Name        │          │ Abbott, Master. Eugene Joseph │         │
│ 4   │ Sex         │          │ female                        │         │
│ 5   │ Age         │ 30.4222  │ 0.17                          │ 31.0    │
│ 6   │ SibSp       │ 0.447368 │ 0                             │ 0.0     │
│ 7   │ Parch       │ 0.392344 │ 0                             │ 0.0     │
│ 8   │ Ticket      │          │ 110469                        │         │
│ 9   │ Fare        │ 35.6257  │ 0.0                           │ 14.4542 │
│ 10  │ Embarked    │          │ C                             │         │

│ Row │ m

In [27]:
names(train)

11-element Array{String,1}:
 "PassengerId"
 "Survived"
 "Pclass"
 "Name"
 "Sex"
 "Age"
 "SibSp"
 "Parch"
 "Ticket"
 "Fare"
 "Embarked"

In [28]:
names(test)

10-element Array{String,1}:
 "PassengerId"
 "Pclass"
 "Name"
 "Sex"
 "Age"
 "SibSp"
 "Parch"
 "Ticket"
 "Fare"
 "Embarked"

In [29]:
maps =labelmap(train["Sex"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[29]:1
└ @ Core In[29]:1


LabelMap (with 2 labels):
[1] male
[2] female


In [30]:
train["Sex"] =labelencode(maps,train["Sex"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[30]:1
└ @ Core In[30]:1
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = top-level scope at In[30]:1
└ @ Core In[30]:1


891-element Array{Int64,1}:
 1
 2
 2
 2
 1
 1
 1
 1
 2
 2
 2
 2
 1
 ⋮
 2
 2
 1
 2
 1
 1
 2
 1
 2
 2
 1
 1

In [31]:
mapss =labelmap(test["Sex"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[31]:1
└ @ Core In[31]:1


LabelMap (with 2 labels):
[1] male
[2] female


In [32]:
test["Sex"] =labelencode(mapss,test["Sex"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[32]:1
└ @ Core In[32]:1
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = top-level scope at In[32]:1
└ @ Core In[32]:1


418-element Array{Int64,1}:
 1
 2
 1
 1
 2
 1
 2
 1
 2
 1
 1
 1
 2
 ⋮
 1
 1
 2
 2
 2
 2
 2
 1
 2
 1
 1
 1

In [33]:
embarked_maps= labelmap(train["Embarked"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[33]:1
└ @ Core In[33]:1


LabelMap (with 3 labels):
[1] S
[2] C
[3] Q


In [34]:
train["Embarked"] = labelencode(embarked_maps,train["Embarked"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[34]:1
└ @ Core In[34]:1
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = top-level scope at In[34]:1
└ @ Core In[34]:1


891-element Array{Int64,1}:
 1
 2
 1
 1
 1
 3
 1
 1
 1
 2
 1
 1
 1
 ⋮
 2
 1
 1
 1
 1
 1
 3
 1
 1
 1
 2
 3

In [35]:
test["Embarked"] = labelencode(embarked_maps,test["Embarked"])

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[35]:1
└ @ Core In[35]:1
┌ Warning: `setindex!(df::DataFrame, v::AbstractVector, col_ind::ColumnIndex)` is deprecated, use `begin
│     df[!, col_ind] = v
│     df
│ end` instead.
│   caller = top-level scope at In[35]:1
└ @ Core In[35]:1


418-element Array{Int64,1}:
 3
 1
 3
 1
 1
 1
 3
 1
 2
 1
 1
 1
 1
 ⋮
 1
 2
 3
 1
 3
 3
 1
 1
 2
 1
 1
 2

In [36]:
select!(train,Not(:Ticket))

891×10 DataFrame. Omitted printing of 7 columns
│ Row │ PassengerId │ Survived │ Pclass │
│     │ Int64       │ Int64    │ Int64  │
├─────┼─────────────┼──────────┼────────┤
│ 1   │ 1           │ 0        │ 3      │
│ 2   │ 2           │ 1        │ 1      │
│ 3   │ 3           │ 1        │ 3      │
│ 4   │ 4           │ 1        │ 1      │
│ 5   │ 5           │ 0        │ 3      │
│ 6   │ 6           │ 0        │ 3      │
│ 7   │ 7           │ 0        │ 1      │
│ 8   │ 8           │ 0        │ 3      │
│ 9   │ 9           │ 1        │ 3      │
│ 10  │ 10          │ 1        │ 2      │
⋮
│ 881 │ 881         │ 1        │ 2      │
│ 882 │ 882         │ 0        │ 3      │
│ 883 │ 883         │ 0        │ 3      │
│ 884 │ 884         │ 0        │ 2      │
│ 885 │ 885         │ 0        │ 3      │
│ 886 │ 886         │ 0        │ 3      │
│ 887 │ 887         │ 0        │ 2      │
│ 888 │ 888         │ 1        │ 1      │
│ 889 │ 889         │ 0        │ 3      │
│ 890 │ 890         │ 1        │ 1      │
│ 891 │ 891         │ 0        │ 3      │

In [37]:
select!(test,Not(:Ticket))

418×9 DataFrame. Omitted printing of 6 columns
│ Row │ PassengerId │ Pclass │ Name                                            │
│     │ Int64       │ Int64  │ String                                          │
├─────┼─────────────┼────────┼─────────────────────────────────────────────────┤
│ 1   │ 892         │ 3      │ Kelly, Mr. James                                │
│ 2   │ 893         │ 3      │ Wilkes, Mrs. James (Ellen Needs)                │
│ 3   │ 894         │ 2      │ Myles, Mr. Thomas Francis                       │
│ 4   │ 895         │ 3      │ Wirz, Mr. Albert                                │
│ 5   │ 896         │ 3      │ Hirvonen, Mrs. Alexander (Helga E Lindqvist)    │
│ 6   │ 897         │ 3      │ Svensson, Mr. Johan Cervin                      │
│ 7   │ 898         │ 3      │ Connolly, Miss. Kate                            │
│ 8   │ 899         │ 2      │ Caldwell, Mr. Albert Francis                    │
│ 9   │ 900         │ 3      │ Abrahim, Mrs. Joseph (Sophie Halaut Easu)       │
│ 10  │ 901         │ 3      │ Davies, Mr. John Samuel                         │
⋮
│ 408 │ 1299        │ 1      │ Widener, Mr. George Dunton                      │
│ 409 │ 1300        │ 3      │ Riordan, Miss. Johanna Hannah""                 │
│ 410 │ 1301        │ 3      │ Peacock, Miss. Treasteall                       │
│ 411 │ 1302        │ 3      │ Naughton, Miss. Hannah                          │
│ 412 │ 1303        │ 1      │ Minahan, Mrs. William Edward (Lillian E Thorpe) │
│ 413 │ 1304        │ 3      │ Henriksson, Miss. Jenny Lovisa                  │
│ 414 │ 1305        │ 3      │ Spector, Mr. Woolf                              │
│ 415 │ 1306        │ 1      │ Oliva y Ocana, Dona. Fermina                    │
│ 416 │ 1307        │ 3      │ Saether, Mr. Simon Sivertsen                    │
│ 417 │ 1308        │ 3      │ Ware, Mr. Frederick                             │
│ 418 │ 1309        │ 3      │ Peter, Master. Michael J                        │

In [38]:
y=train["Survived"]

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[38]:1
└ @ Core In[38]:1


891-element Array{Int64,1}:
 0
 1
 1
 1
 0
 0
 0
 0
 1
 1
 1
 1
 0
 ⋮
 1
 1
 0
 0
 0
 0
 0
 0
 1
 0
 1
 0

In [39]:
select!(train,Not(:Survived))

891×9 DataFrame. Omitted printing of 7 columns
│ Row │ PassengerId │ Pclass │
│     │ Int64       │ Int64  │
├─────┼─────────────┼────────┤
│ 1   │ 1           │ 3      │
│ 2   │ 2           │ 1      │
│ 3   │ 3           │ 3      │
│ 4   │ 4           │ 1      │
│ 5   │ 5           │ 3      │
│ 6   │ 6           │ 3      │
│ 7   │ 7           │ 1      │
│ 8   │ 8           │ 3      │
│ 9   │ 9           │ 3      │
│ 10  │ 10          │ 2      │
⋮
│ 881 │ 881         │ 2      │
│ 882 │ 882         │ 3      │
│ 883 │ 883         │ 3      │
│ 884 │ 884         │ 2      │
│ 885 │ 885         │ 3      │
│ 886 │ 886         │ 3      │
│ 887 │ 887         │ 2      │
│ 888 │ 888         │ 1      │
│ 889 │ 889         │ 3      │
│ 890 │ 890         │ 1      │
│ 891 │ 891         │ 3      │

In [40]:
id = test["PassengerId"]

┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = top-level scope at In[40]:1
└ @ Core In[40]:1


418-element Array{Int64,1}:
  892
  893
  894
  895
  896
  897
  898
  899
  900
  901
  902
  903
  904
    ⋮
 1298
 1299
 1300
 1301
 1302
 1303
 1304
 1305
 1306
 1307
 1308
 1309

In [41]:
select!(train,Not(:PassengerId))

891×8 DataFrame. Omitted printing of 5 columns
│ Row │ Pclass │ Name                                                │ Sex   │
│     │ Int64  │ String                                              │ Int64 │
├─────┼────────┼─────────────────────────────────────────────────────┼───────┤
│ 1   │ 3      │ Braund, Mr. Owen Harris                             │ 1     │
│ 2   │ 1      │ Cumings, Mrs. John Bradley (Florence Briggs Thayer) │ 2     │
│ 3   │ 3      │ Heikkinen, Miss. Laina                              │ 2     │
│ 4   │ 1      │ Futrelle, Mrs. Jacques Heath (Lily May Peel)        │ 2     │
│ 5   │ 3      │ Allen, Mr. William Henry                            │ 1     │
│ 6   │ 3      │ Moran, Mr. James                                    │ 1     │
│ 7   │ 1      │ McCarthy, Mr. Timothy J                             │ 1     │
│ 8   │ 3      │ Palsson, Master. Gosta Leonard                      │ 1     │
│ 9   │ 3      │ Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   │ 2     │
│ 10  │ 2      │ Nasser, Mrs. Nicholas (Adele Achem)                 │ 2     │
⋮
│ 881 │ 2      │ Shelley, Mrs. William (Imanita Parrish Hall)        │ 2     │
│ 882 │ 3      │ Markun, Mr. Johann                                  │ 1     │
│ 883 │ 3      │ Dahlberg, Miss. Gerda Ulrika                        │ 2     │
│ 884 │ 2      │ Banfield, Mr. Frederick James                       │ 1     │
│ 885 │ 3      │ Sutehall, Mr. Henry Jr                              │ 1     │
│ 886 │ 3      │ Rice, Mrs. William (Margaret Norton)                │ 2     │
│ 887 │ 2      │ Montvila, Rev. Juozas                               │ 1     │
│ 888 │ 1      │ Graham, Miss. Margaret Edith                        │ 2     │
│ 889 │ 3      │ Johnston, Miss. Catherine Helen "Carrie"            │ 2     │
│ 890 │ 1      │ Behr, Mr. Karl Howell                               │ 1     │
│ 891 │ 3      │ Dooley, Mr. Patrick                                 │ 1     │

In [42]:
select!(test,Not(:PassengerId))

418×8 DataFrame. Omitted printing of 5 columns
│ Row │ Pclass │ Name                                            │ Sex   │
│     │ Int64  │ String                                          │ Int64 │
├─────┼────────┼─────────────────────────────────────────────────┼───────┤
│ 1   │ 3      │ Kelly, Mr. James                                │ 1     │
│ 2   │ 3      │ Wilkes, Mrs. James (Ellen Needs)                │ 2     │
│ 3   │ 2      │ Myles, Mr. Thomas Francis                       │ 1     │
│ 4   │ 3      │ Wirz, Mr. Albert                                │ 1     │
│ 5   │ 3      │ Hirvonen, Mrs. Alexander (Helga E Lindqvist)    │ 2     │
│ 6   │ 3      │ Svensson, Mr. Johan Cervin                      │ 1     │
│ 7   │ 3      │ Connolly, Miss. Kate                            │ 2     │
│ 8   │ 2      │ Caldwell, Mr. Albert Francis                    │ 1     │
│ 9   │ 3      │ Abrahim, Mrs. Joseph (Sophie Halaut Easu)       │ 2     │
│ 10  │ 3      │ Davies, Mr. John Samuel                         │ 1     │
⋮
│ 408 │ 1      │ Widener, Mr. George Dunton                      │ 1     │
│ 409 │ 3      │ Riordan, Miss. Johanna Hannah""                 │ 2     │
│ 410 │ 3      │ Peacock, Miss. Treasteall                       │ 2     │
│ 411 │ 3      │ Naughton, Miss. Hannah                          │ 2     │
│ 412 │ 1      │ Minahan, Mrs. William Edward (Lillian E Thorpe) │ 2     │
│ 413 │ 3      │ Henriksson, Miss. Jenny Lovisa                  │ 2     │
│ 414 │ 3      │ Spector, Mr. Woolf                              │ 1     │
│ 415 │ 1      │ Oliva y Ocana, Dona. Fermina                    │ 2     │
│ 416 │ 3      │ Saether, Mr. Simon Sivertsen                    │ 1     │
│ 417 │ 3      │ Ware, Mr. Frederick                             │ 1     │
│ 418 │ 3      │ Peter, Master. Michael J                        │ 1     │

In [43]:
select!(train,Not(:Name))

891×7 DataFrame
│ Row │ Pclass │ Sex   │ Age     │ SibSp │ Parch │ Fare    │ Embarked │
│     │ Int64  │ Int64 │ Float64 │ Int64 │ Int64 │ Float64 │ Int64    │
├─────┼────────┼───────┼─────────┼───────┼───────┼─────────┼──────────┤
│ 1   │ 3      │ 1     │ 22.0    │ 1     │ 0     │ 7.25    │ 1        │
│ 2   │ 1      │ 2     │ 38.0    │ 1     │ 0     │ 71.2833 │ 2        │
│ 3   │ 3      │ 2     │ 26.0    │ 0     │ 0     │ 7.925   │ 1        │
│ 4   │ 1      │ 2     │ 35.0    │ 1     │ 0     │ 53.1    │ 1        │
│ 5   │ 3      │ 1     │ 35.0    │ 0     │ 0     │ 8.05    │ 1        │
│ 6   │ 3      │ 1     │ 30.0    │ 0     │ 0     │ 8.4583  │ 3        │
│ 7   │ 1      │ 1     │ 54.0    │ 0     │ 0     │ 51.8625 │ 1        │
│ 8   │ 3      │ 1     │ 2.0     │ 3     │ 1     │ 21.075  │ 1        │
│ 9   │ 3      │ 2     │ 27.0    │ 0     │ 2     │ 11.1333 │ 1        │
│ 10  │ 2      │ 2     │ 14.0    │ 1     │ 0     │ 30.0708 │ 2        │
⋮
│ 881 │ 2      │ 2     │ 25.0    │ 0     │ 1     │ 26.0    │ 1        │
│ 882 │ 3      │ 1     │ 33.0    │ 0     │ 0     │ 7.8958  │ 1        │
│ 883 │ 3      │ 2     │ 22.0    │ 0     │ 0     │ 10.5167 │ 1        │
│ 884 │ 2      │ 1     │ 28.0    │ 0     │ 0     │ 10.5    │ 1        │
│ 885 │ 3      │ 1     │ 25.0    │ 0     │ 0     │ 7.05    │ 1        │
│ 886 │ 3      │ 2     │ 39.0    │ 0     │ 5     │ 29.125  │ 3        │
│ 887 │ 2      │ 1     │ 27.0    │ 0     │ 0     │ 13.0    │ 1        │
│ 888 │ 1      │ 2     │ 19.0    │ 0     │ 0     │ 30.0    │ 1        │
│ 889 │ 3      │ 2     │ 30.0    │ 1     │ 2     │ 23.45   │ 1        │
│ 890 │ 1      │ 1     │ 26.0    │ 0     │ 0     │ 30.0    │ 2        │
│ 891 │ 3      │ 1     │ 32.0    │ 0     │ 0     │ 7.75    │ 3        │

In [44]:
select!(test,Not(:Name))

418×7 DataFrame
│ Row │ Pclass │ Sex   │ Age     │ SibSp │ Parch │ Fare    │ Embarked │
│     │ Int64  │ Int64 │ Float64 │ Int64 │ Int64 │ Real    │ Int64    │
├─────┼────────┼───────┼─────────┼───────┼───────┼─────────┼──────────┤
│ 1   │ 3      │ 1     │ 34.5    │ 0     │ 0     │ 7.8292  │ 3        │
│ 2   │ 3      │ 2     │ 47.0    │ 1     │ 0     │ 7.0     │ 1        │
│ 3   │ 2      │ 1     │ 62.0    │ 0     │ 0     │ 9.6875  │ 3        │
│ 4   │ 3      │ 1     │ 27.0    │ 0     │ 0     │ 8.6625  │ 1        │
│ 5   │ 3      │ 2     │ 22.0    │ 1     │ 1     │ 12.2875 │ 1        │
│ 6   │ 3      │ 1     │ 14.0    │ 0     │ 0     │ 9.225   │ 1        │
│ 7   │ 3      │ 2     │ 30.0    │ 0     │ 0     │ 7.6292  │ 3        │
│ 8   │ 2      │ 1     │ 26.0    │ 1     │ 1     │ 29.0    │ 1        │
│ 9   │ 3      │ 2     │ 18.0    │ 0     │ 0     │ 7.2292  │ 2        │
│ 10  │ 3      │ 1     │ 21.0    │ 2     │ 0     │ 24.15   │ 1        │
⋮
│ 408 │ 1      │ 1     │ 50.0    │ 1     │ 1     │ 211.5   │ 2        │
│ 409 │ 3      │ 2     │ 31.0    │ 0     │ 0     │ 7.7208  │ 3        │
│ 410 │ 3      │ 2     │ 3.0     │ 1     │ 1     │ 13.775  │ 1        │
│ 411 │ 3      │ 2     │ 31.0    │ 0     │ 0     │ 7.75    │ 3        │
│ 412 │ 1      │ 2     │ 37.0    │ 1     │ 0     │ 90.0    │ 3        │
│ 413 │ 3      │ 2     │ 28.0    │ 0     │ 0     │ 7.775   │ 1        │
│ 414 │ 3      │ 1     │ 31.0    │ 0     │ 0     │ 8.05    │ 1        │
│ 415 │ 1      │ 2     │ 39.0    │ 0     │ 0     │ 108.9   │ 2        │
│ 416 │ 3      │ 1     │ 38.5    │ 0     │ 0     │ 7.25    │ 1        │
│ 417 │ 3      │ 1     │ 31.0    │ 0     │ 0     │ 8.05    │ 1        │
│ 418 │ 3      │ 1     │ 31.0    │ 1     │ 1     │ 22.3583 │ 2        │

In [45]:
train_x = convert(Array,train[:,:])

891×7 Array{Float64,2}:
 3.0  1.0  22.0  1.0  0.0   7.25    1.0
 1.0  2.0  38.0  1.0  0.0  71.2833  2.0
 3.0  2.0  26.0  0.0  0.0   7.925   1.0
 1.0  2.0  35.0  1.0  0.0  53.1     1.0
 3.0  1.0  35.0  0.0  0.0   8.05    1.0
 3.0  1.0  30.0  0.0  0.0   8.4583  3.0
 1.0  1.0  54.0  0.0  0.0  51.8625  1.0
 3.0  1.0   2.0  3.0  1.0  21.075   1.0
 3.0  2.0  27.0  0.0  2.0  11.1333  1.0
 2.0  2.0  14.0  1.0  0.0  30.0708  2.0
 3.0  2.0   4.0  1.0  1.0  16.7     1.0
 1.0  2.0  58.0  0.0  0.0  26.55    1.0
 3.0  1.0  20.0  0.0  0.0   8.05    1.0
 ⋮                          ⋮       
 1.0  2.0  56.0  0.0  1.0  83.1583  2.0
 2.0  2.0  25.0  0.0  1.0  26.0     1.0
 3.0  1.0  33.0  0.0  0.0   7.8958  1.0
 3.0  2.0  22.0  0.0  0.0  10.5167  1.0
 2.0  1.0  28.0  0.0  0.0  10.5     1.0
 3.0  1.0  25.0  0.0  0.0   7.05    1.0
 3.0  2.0  39.0  0.0  5.0  29.125   3.0
 2.0  1.0  27.0  0.0  0.0  13.0     1.0
 1.0  2.0  19.0  0.0  0.0  30.0     1.0
 3.0  2.0  30.0  1.0  2.0  23.45    1.0
 1.0  1.0  26.0  0.

In [46]:
train_y=convert(Array,y[:,:])

891×1 Array{Int64,2}:
 0
 1
 1
 1
 0
 0
 0
 0
 1
 1
 1
 1
 0
 ⋮
 1
 1
 0
 0
 0
 0
 0
 0
 1
 0
 1
 0

In [47]:
first(train,3)

3×7 DataFrame
│ Row │ Pclass │ Sex   │ Age     │ SibSp │ Parch │ Fare    │ Embarked │
│     │ Int64  │ Int64 │ Float64 │ Int64 │ Int64 │ Float64 │ Int64    │
├─────┼────────┼───────┼─────────┼───────┼───────┼─────────┼──────────┤
│ 1   │ 3      │ 1     │ 22.0    │ 1     │ 0     │ 7.25    │ 1        │
│ 2   │ 1      │ 2     │ 38.0    │ 1     │ 0     │ 71.2833 │ 2        │
│ 3   │ 3      │ 2     │ 26.0    │ 0     │ 0     │ 7.925   │ 1        │

In [48]:
test_x=convert(Array,test[:,:])

418×7 Array{Real,2}:
 3  1  34.5  0  0    7.8292  3
 3  2  47.0  1  0    7.0     1
 2  1  62.0  0  0    9.6875  3
 3  1  27.0  0  0    8.6625  1
 3  2  22.0  1  1   12.2875  1
 3  1  14.0  0  0    9.225   1
 3  2  30.0  0  0    7.6292  3
 2  1  26.0  1  1   29.0     1
 3  2  18.0  0  0    7.2292  2
 3  1  21.0  2  0   24.15    1
 3  1  31.0  0  0    7.8958  1
 1  1  46.0  0  0   26.0     1
 1  2  23.0  1  0   82.2667  1
 ⋮                   ⋮       
 2  1  23.0  1  0   10.5     1
 1  1  50.0  1  1  211.5     2
 3  2  31.0  0  0    7.7208  3
 3  2   3.0  1  1   13.775   1
 3  2  31.0  0  0    7.75    3
 1  2  37.0  1  0   90.0     3
 3  2  28.0  0  0    7.775   1
 3  1  31.0  0  0    8.05    1
 1  2  39.0  0  0  108.9     2
 3  1  38.5  0  0    7.25    1
 3  1  31.0  0  0    8.05    1
 3  1  31.0  1  1   22.3583  2

In [49]:
@sk_import tree:DecisionTreeClassifier

PyObject <class 'sklearn.tree._classes.DecisionTreeClassifier'>

In [50]:
tree = DecisionTreeClassifier()

PyObject DecisionTreeClassifier()

In [60]:
fit!(tree,train_x,train_y)

PyObject DecisionTreeClassifier()

In [61]:
tree_pred = predict(tree,test_x)

418-element Array{Int64,1}:
 0
 0
 1
 1
 1
 0
 0
 0
 1
 0
 0
 0
 1
 ⋮
 0
 0
 0
 0
 0
 1
 0
 1
 1
 0
 1
 0